FROM docker.elastic.co/elasticsearch/elasticsearch:8.5.1 

ENV node.name=es
ENV cluster.name=docker-cluster
ENV bootstrap.memory_lock=true
ENV discovery.type=single-node
ENV ES_JAVA_OPTS="-Xms2g -Xmx2g"

# 
ENV xpack.security.enabled=false
ENV xpack.security.enrollment.enabled=false
ENV xpack.security.http.ssl.enabled=false
ENV xpack.security.transport.ssl.enabled=false

ENV network.host=0.0.0.0
ENV http.port=9200 

RUN bin/elasticsearch-plugin install analysis-nori

#VOLUME /usr/share/elasticsearch/data

#EXPOSE 9200